apiVersion: v2
name: platforma
description: A Helm chart for Platforma application
type: application
version: 2.1.0
appVersion: "1.42.2"
kubeVersion: ">=1.25.0-0"
icon: "https://raw.githubusercontent.com/milaboratory/platforma-helm-charts/main/charts/platforma/logo.svg"
sources:
  - https://github.com/milaboratory/platforma-helm-charts/charts/platforma
home: https://github.com/milaboratory/platforma-helm-charts
keywords:
  - milaboratories
  - platforma
  - kubernetes
annotations:
  artifacthub.io/links: |-
    - name: Sources
      url: https://platforma.bio/downloads/
    - name: Charts repository
      url: https://github.com/milaboratory/platforma-helm-charts
    - name: Docs
      url: https://docs.platforma.bio/
dependencies:
  - name: victoria-logs-single           
    version: 0.11.8                       
    repository: https://victoriametrics.github.io/helm-charts
    alias: victoria-logs
    condition: victoria-logs.enabled 
  - name: victoria-logs-collector           
    version: 0.0.5
    repository: https://victoriametrics.github.io/helm-charts
    alias: victoria-logs-collector
    condition: victoria-logs-collector.enabled 