apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.app.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "glauth.labels" . | nindent 4 }}
    {{- with .Values.app.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "glauth.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "glauth.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.app.replicaCount }}
  {{- with .Values.app.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/app-secret-config.yaml") . | sha256sum }}
      {{- with .Values.app.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- include "glauth.labels" . | nindent 8 }}
      {{- with .Values.app.podLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.app.priorityClassName }}
      priorityClassName: {{ .Values.app.priorityClassName | toString }}
      {{- end }}
      {{- if .Values.app.schedulerName }}
      schedulerName: {{ .Values.app.schedulerName }}
      {{- end }}
      {{- if .Values.app.enableServiceLinks }}
      enableServiceLinks: {{ .Values.app.enableServiceLinks }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- with .Values.app.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.app.terminationGracePeriodSeconds }}
      containers:
        - name: {{ template "glauth.name" . }}-{{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ include "glauth.imageTag" . }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          {{- if .Values.app.containerWorkingDir }}
          workingDir: {{ .Values.app.containerWorkingDir }}
          {{- end }}
          {{- with .Values.app.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.app.image.command }}
          command: [{{ .Values.app.image.command | quote }}]
          {{- end }}
          {{- if .Values.app.image.args }}
          args:
          {{- range .Values.app.image.args }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.app.env }}
          env:
          {{- range $key, $value := .Values.app.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.app.envValueFrom }}
          {{- range $key, $value := .Values.app.envValueFrom }}
            - name: {{ $key | quote }}
              valueFrom:
                {{- tpl (toYaml $value) $ | nindent 16 }}
          {{- end }}
          {{- end }}
          ports:
            - name: {{ .Values.app.service.portName }}
              containerPort: {{ .Values.app.service.targetPort }}
          {{- with .Values.app.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12  }}
          {{- end }}
          {{- with .Values.app.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12  }}
          {{- end }}
          {{- with .Values.app.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config/config.cfg
              subPath: config.cfg
              readOnly: true
            - name: database-volume
              mountPath: {{ .Values.app.persistentVolume.mountPath }}
      {{- with .Values.app.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.app.hostAliases }}
      hostAliases:
{{ toYaml . | indent 8 }}
      {{- end }}
      serviceAccountName: {{ template "glauth.serviceAccountName" . }}
      {{- with .Values.app.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.app.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml . | indent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.app.hostNetwork }}
      {{- if .Values.app.dnsPolicy }}
      dnsPolicy: {{ .Values.app.dnsPolicy | toString }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
{{- toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ template "glauth.fullname" . }}-secret-config
        - name: database-volume
        {{- if .Values.app.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.app.persistentVolume.existingClaim }}{{ .Values.app.persistentVolume.existingClaim }}{{- else }}{{ template "glauth.fullname" . }}{{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
