{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "glauth.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glauth.labels" . | nindent 4 }}
    {{- with .Values.rbac.extraLabels }}
    {{- toYaml . | nindent 4}}
    {{- end }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules: []
{{- end }}
