{{- if .Values.app.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  {{- with .Values.app.externalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "platforma.labels" . | nindent 4 }}
    {{- with .Values.app.externalSecret.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "platforma.fullname" . }}-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.app.externalSecret.secretRefreshInterval }}
  secretStoreRef:
    name: {{ template "platforma.fullname" . }}-secretstore
    kind: SecretStore
  target:
    name: {{ .Values.app.externalSecret.secretStoreTarget }}
    creationPolicy: Owner
  data:
  {{- range $key, $value := .Values.app.externalSecret.secretDataFrom }}
  - secretKey: {{ $key }}
    remoteRef:
       {{- tpl (toYaml $value) $ | nindent 8 }}
  {{- end }}
{{- end }}
