{{- if .Values.app.horizontalPodAutoscaler.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "platforma.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platforma.labels" . | nindent 4 }}
    {{- with .Values.app.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "platforma.fullname" . }}
  minReplicas: {{ .Values.app.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.app.horizontalPodAutoscaler.maxReplicas }}
  metrics:
{{ toYaml .Values.app.horizontalPodAutoscaler.metrics | indent 4 }}
{{- end }}
