{{- if eq .Values.app.coreConfig.auth.type "htpasswd" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "platforma.fullname" . }}-htpasswd-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platforma.labels" . | nindent 4 }}
type: Opaque
data:
  users.htpasswd: {{ .Values.app.htpasswdConfig | b64enc | quote }}
{{- end }}  
