{{- if .Values.app.istio.enabled }}
{{- $istioHosts := .Values.app.istio.hosts }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "platforma.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platforma.labels" . | nindent 4 }}
    {{- with .Values.app.istio.gateway.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    istio: {{ .Values.app.istio.gateway.ingressGatewayName }}
  servers:
    - port:
        number: {{ .Values.app.istio.gateway.port }}
        name: {{ .Values.app.istio.gateway.portName }}
        protocol: {{ .Values.app.istio.gateway.protocol }}
      hosts:
        {{- range $istioHosts }}
        - {{ tpl . $ | quote }}
        {{- end }}
{{- end }}