{{- if .Values.app.podDisruptionBudget.enabled }}
apiVersion: {{ include "platforma.podDisruptionBudget.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "platforma.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platforma.labels" . | nindent 4 }}
    {{- with .Values.app.podDisruptionBudget.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
{{- with .Values.app.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
{{- end }}
{{- with .Values.app.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
{{- end }}
  selector:
    matchLabels:
      {{- include "platforma.selectorLabels" . | nindent 6 }}
{{- end }}
