apiVersion: v1
kind: Service
metadata:
  name: {{ template "platforma.fullname" . }}-debug
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platforma.labels" . | nindent 4 }}
    {{- with .Values.app.debug.service.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .Values.app.debug.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if .Values.app.debug.service.clusterIP }}
  clusterIP: {{ .Values.app.debug.service.clusterIP }}
{{- end }}
{{- if .Values.app.debug.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.app.debug.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.app.debug.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.app.debug.service.loadBalancerIP }}
{{- end }}
{{- if .Values.app.debug.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.app.debug.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - name: {{ .Values.app.debug.service.portName }}
      port: {{ .Values.app.debug.service.port }}
      protocol: TCP
      targetPort: {{ .Values.app.debug.service.targetPort }}
      {{- if (and (eq .Values.app.debug.service.type "NodePort") (not (empty .Values.app.debug.service.nodePort))) }}
      nodePort: {{ .Values.app.debug.service.nodePort }}
      {{- end }}
  selector:
    {{- include "platforma.selectorLabels" . | nindent 4 }}
  type: {{ .Values.app.debug.service.type }}
  {{- with .Values.app.debug.service.healthCheckNodePort }}
  healthCheckNodePort: {{ . }}
  {{- end }}
  {{- with .Values.app.debug.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
