{{- if .Values.app.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  {{- with .Values.app.externalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "platforma.labels" . | nindent 4 }}
    {{- with .Values.app.externalSecret.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "platforma.fullname" . }}-secretstore
  namespace: {{ .Release.Namespace }}
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.app.externalSecret.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ template "platforma.serviceAccountName" . }}
{{- end }}
