{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "platforma.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platforma.labels" . | nindent 4 }}
    {{- with .Values.rbac.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "platforma.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "platforma.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}